### ISSUE TITLE
only computer traffic

### ISSUE THREAD

**Issue by ticoti** [powerthazan/YOURLS-GA-MP-Tracking#7]
It does only appears the traffic as computer source, not mobile or tablet

**Comment by powerthazan** [comment]
It is depend on your parameters. Eg: In  `$data` array, Add `&ua=Opera/9.80 // User agent override`  to send user browser. You can use other parameter as your wish. However, you need to determine User Device manually before send hit.
 Please refer further here: [https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide](url)  and Here: [https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters](url)
